version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.fe
    ports:
      - "4200:80"
    container_name: angular_fe

  backend:
    build:
      context: .
      dockerfile: Dockerfile.be
    ports:
      - "5000:5000"
    container_name: dotnet_be

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # Cho phép Jenkins dùng Docker host
    restart: always

volumes:
  jenkins_home:
